### ISSUE TITLE
Fix lstopo graphical exponential complexity

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#121]
On my laptop (dual-core, hyperthreaded), pu_draw() gets called 7164 times, and core_draw 1790, but they just draw 6 boxes in the end. In general, each object at depth N get its foo_draw() function called (7x2^N)-1 times.

The reason is that every object does a first recurse into its entire subtree without drawing, then draws its own box, and then recurse again with drawing. That's an exponential multi-recursion.

Ideally, we should recurse in the tree once without drawing, go back to the top, and then recurse again with drawing. Only recurse twice from the top, no need to recurse twice in every object.

Likely only matters for people that display dynamic information in lstopo, but could be a good opportunity to make the code more readable and flexible. Got an intern?

**Comment by sthibaul** [comment]
Well, the problem is NP-complete, so unless using heuristics, you can't
avoid exponential things. But several thousands for a laptop is a
problem indeed :)

There is already dynamic programming support in there to avoid this,
see the DYNA_SAVE and DYNA_CHECK macros, which already avoid computing
anything several times.  I guess this is what is broken.  Reading the
source again, I don't see why we free the userdata which is precisely
supposed to store the dynamic information, see the attached patch.

**Comment by sthibaul** [comment]
GRrr, isn't there a way to attach a file on this bug tracker??

Anyway, here are the lines:
-    free(level->userdata); \
-    level->userdata = NULL; \
+    /* free(level->userdata); */ \
+    /* level->userdata = NULL; */ \

**Comment by bgoglin** [comment]
Down to 16 pu_draw() and 8 core_draw(), thanks :)

**Comment by jsquyres** [comment]
Fwiw, it's usually easiest to paste patches in gist and then put the link in the github issue.

Sent from my phone. No type good.

On Feb 5, 2015, at 4:55 AM, Samuel Thibault <notifications@github.com<mailto:notifications@github.com>> wrote:


GRrr, isn't there a way to attach a file on this bug tracker??

Anyway, here are the lines:

  *   free(level->userdata); \
  *   level->userdata = NULL; \
  *   /* free(level->userdata); */ \
  *   /* level->userdata = NULL; */ \
