### ISSUE TITLE
Don't break multithreaded process individual thread binding during x86 discovery

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#158]
The x86 backend changes the current thread binding to run CPUID discovery on each PU. If the OS supports process binding but not thread binding, we bind the entire process and later restore its original binding. If the caller is a multithreaded program, that means each individual thread binding is changed to the original process binding. Not good if individual threads were already specifically bound (got one bug report like this).

Before v1.11.3, we tried process binding first, so this problem always occurred. Since commit 22e16ae67e785d097afd4694813e1a9226785bd0 (backported in v1.11.3), we try thread binding first. And we have no OS that supports process binding without thread binding. So the problem should be hidden for now.

Ideally, one of these solutions would be better:
- Only use process binding if the process is monothread. How do we know?
- Have a way to restore individual thread bindings. Requires to also restore the binding of threads that were created in the middle of the x86 discovery (those get rebound only in the iterations of the discovery).
- Have a topology flag saying "don't rebind the process and/or thread during discovery" which just disables the x86 backend if too dangerous

The problem will also be further mitigated in v2.x by adding topology flags saying what the userwants to do. If he just wants to bind things, the x86 backend is totally useless on Linux since annotations are useless. If he just needs to bind things on PUs/Core/NUMA, the x86 backend is useless on any OS whose backends already supports PU/Core/NUMA.

**Comment by sthibaul** [comment]
> Only use process binding if the process is monothread. How do we know?

There is no standard way to know. At best one can use a weak reference to pthread_create to detect whether libpthread was linked in or not, but having libpthread linked in does not mean it is multithreaded.

> Have a way to restore individual thread bindings.

Mmm, but then it'd mean we have support for thread binding, and thus we wouldn't use process binding.

In the end I'd say the least dangerous would be to avoid process binding as soon as libpthread is linked it. That'd disable the x86 backend on systems without thread binding for any program which happens to link against libpthread, but I guess that's a rare enough thing.

**Comment by zwieberl** [comment]
Slightly related, as its the x86 backend that caused this problem on Linux:
Our daemon using hwloc is periodically getting the topology of the system (not ideal, I know), and the x86 component caused the daemon to change its binding all the time, which really hurt performance.

One can also see this with the `hwloc-info` binary from the repo.
We upgraded from version 1.3 to 1.11.8. Before that, if you run the `hwloc-info` binary in strace, you  see only one call to `sched_getaffinity()` which is what was expected. 
Starting with 1.6 and onwards, a simple `hwloc-info`-call would cause numerous `sched_Setaffinity()` calls with varying topology. 

Since we do this periodically, performance degraded significantly. An additional problem occurs when one starts the daemon with a given affinity to specifically prohibit it from getting on other cores. With these `sched_Setaffinity()` calls however, it will also get on those cores, sometimes causing trouble.

Our workaround now is to disable the x86 component, by either compiling `hwloc` with `--disable-cpuid`, or by calling the already built binaries with `HWLOC_COMPONENTS=-x86`

**Comment by bgoglin** [comment]
@zwieberl I forgot to say that last year but you should consider using a XML topology instead of having each iteration redo its own discovery. It speeds up discovery and avoids spurious binding changes.

**Comment by bgoglin** [comment]
I am checking the status of this issue for #366. It looks like all OS that have process binding support also have thread binding, so this issue should be gone... in theory. In practice, it looks like windows thread binding can affect process binding (when there are multiple processor groups), hence future threads will inherit this modified process binding. Hence I'll look at adding a new hook dedicated to custom saving/restoring of binding (only used for Windows).

**Comment by bgoglin** [comment]
I am closing this issue since the problem is now Windows specific and things improved recently thanks to new topology flags in 2.5 for disabling binding changes or restricting them to inside the binding. See #471 for a summary of where we are on Windows.
