### ISSUE TITLE
using hwloc on openbsd

### ISSUE THREAD

**Issue by rashadkm** [open-mpi/hwloc#224]
currently openbsd is unsupported by hwloc. This is clear when ruuning configure on openbsd.

I would to know what are exact issues on why hwloc can't be used on obsd? I can build this tool ignore the warning.  But would like to know more.

could someone help?

**Comment by sthibaul** [comment]
As far as we know, openbsd does not provide CPU binding support such as FreeBSD's cpuset_setaffinity or NetBSD's pthread_setaffinity_np. If you can find out some support, we'll be happy to use it, but AFAWK there is none. Perhaps you could contact the OpenBSD community to request the support?

**Comment by rashadkm** [comment]
thanks. I found that cpu affinity discussion on openbsd.  So I am guessing even a successful build on obsd results in no usable binaries. to be fair, configure message was pretty clear on that.  A special thanks on giving explicit warning during configure. Something that these days people kindly ignore.

**Comment by bgoglin** [comment]
You actually get usable binaries, but they are not very useful.
If you scroll to the end of https://ci.inria.fr/hwloc/job/master-1-check/all=OpenBSD_5.2_x86_64/908/console you will see that lstopo shows information about the processor, caches etc. That's on a OpenBSD 5.2 VM without a monoprocessor kernel. Binding isn't needed on such a platform (because there is a single core), hence we can get processor information through CPUID x86 instructions.

I actually just switched to the multiprocessor kernel on that VM. Now we properly detect 2 cores, but we cannot detect processor and cache information anymore (because binding is required for querying individual cores through CPUID).

**Comment by rashadkm** [comment]
thanks @bgoglin for detailed information on this topic. I am trying to get hpx build on openbsd for some testing. hwloc is a requirement for it. As you mentioned libraries built are useful, i can test this.
