### ISSUE TITLE
Single System image

### ISSUE THREAD

**Issue by htbase** [open-mpi/hwloc#259]
Hi team

can we use hwloc to provide us with a single system image? or is it completely different utilization target?

Thanks

**Comment by bgoglin** [comment]
Hello

Not sure what you exactly want. Do you want a single view of multiple machines?

hwloc v1.x can assemble multiple nodes topologies in a single one to have an entire cluster of machines in a single topology, but that's not actually very that nice because:
* hwloc relies heavily on "cpusets" for describind object localion, but cpusets are local to a single machine, so many functions in the API don't work anymore on the multinode topology, and it makes the hwloc core very complex just to make that tiny corner case work
* binding tasks or memory is always a local operation anyway, so manipulating a multinode topology is useless there
* the physical topology of the network cannot be properly represented as a hwloc tree

That's the main reason why we're dropping this feature from 2.0 (and why the network side is being replaced by netloc which doesn't use a tree anymore). But some people basically reimplement that multinode stuff on top of hwloc since they only need the "tree" without the cpusets, binding, etc.

In case it matters, hwloc 1.x also has support for the "kerrighed" single-system image operating system, but it's also being removed in 2.0 because kerrighed is now dead.

Does this help?

**Comment by htbase** [comment]
I believe it does

We are looking at more stable options than Kerrighed, as it has been discontinued but what we want to do is exactly bind cpu and memory from multiple nodes and present it as a single machine / operating system

**Comment by bgoglin** [comment]
OK. hwloc is not going to do that anytime soon. Moving processes across machine requires quite a lot of work, even if you only move at process startup (like MOSIX did) and not later.

**Comment by htbase** [comment]
Thank you

Any suggestions on what to use to achieve that?



On Aug 24, 2017, at 1:08 AM, Brice Goglin <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. hwloc is not going to do that anytime soon. Moving processes across machine requires quite a lot of work, even if you only move at process startup (like MOSIX did) and not later.

**Comment by bgoglin** [comment]
I am closing this issue since there's nothing hwloc can do here.

This was a very active area 15 years ago but it looks like most project have been abandoned now. SSI brings many technical issues (and also performance issues when synchronization OS objects between hosts).
