### ISSUE TITLE
Use rdtscp to get current cpu location when available

### ISSUE THREAD

**Issue by a-denis** [open-mpi/hwloc#261]
Hi,
hwloc reads the content of /proc/ to get cpu location in hwloc_get_last_cpu_location(), which is expensive.
Recent processors have the 'rdtscp' instruction that gives both the tsc and the cpu location in a single instruction. It should be much more efficient than reading /proc/
Thanks!

**Comment by a-denis** [comment]
There's instruction 'rdpid' too, to only get cpu location, but 'rdtscp' seems more widely available.

**Comment by bgoglin** [comment]
Thanks, I am merging this with #147 which has other similar ideas.

**Comment by bgoglin** [comment]
Can you benchmark rdtscp vs sched_getcpu()? It's virtual syscall on top of rdpid or lsl on Linux:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/include/asm/vgtod.h#n83
It says lsl is faster than rdtscp, and works on all CPUs. So it looks like a very good solution.

I couldn't find a machine with rdpid (google talks about cannonlake only?). rdtscp works, but it returns 0x101b instead of 0x1b on my machine, we must apply "& 0xfff". The contents of the TSC_AUX MSR is OS-defined. It's currently "node>>12|cpu" on Linux, but it could change. And it will likely be different on other OSes. So we'll need a way to make sure the kernel didn't get modified before using that.

**Comment by a-denis** [comment]
A quick benchmark gives 18ns for sched_getcpu() and 13ns for rdtscp. It's probably safer to use sched_getcpu().
I can probably build my own table: sched_getcpu() -> hwloc_obj_t

**Comment by bgoglin** [comment]
Thanks. 
hwloc_get_pu_obj_by_os_index() can convert sched_getcpu() into a PU object (but it's a dumb traversal of the list of PUs).
