### ISSUE TITLE
choose dlopen rather than libltdl

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/hwloc#262]
Now that hwloc uses plugins, I'd love to be able to request dlopen rather than libltdl style opening of shared libraries (i.e. plugins) at configure time, similar to Open MPI's framework to do this.

**Comment by jsquyres** [comment]
Hey, that's a great idea.

@gpaulsen Got a patch brewing / ready to file a PR?  😄

**Comment by gpaulsen** [comment]
We have an internal hack, that's not PR worthy, and I don't have time to do it the right way for now, hense the request....

**Comment by bgoglin** [comment]
Jeff is responsible for us using libltdl when plugins were added 5 years ago. I don't remember the pros and cons. Can you elaborate?

**Comment by jsquyres** [comment]
@gpaulsen Can you clarify the use case?  Specifically, I thought that the hwloc bundled in Open MPI never used the DSO plugin functionality...?

**Comment by bgoglin** [comment]
@gpaulsen can you answer @jsquyres questions above?

**Comment by gpaulsen** [comment]
Oh sorry.   So, Spectrum MPI is building hwloc with cuda support as a plugin so that it works on systems without CUDA installed, but has access to the enhanced CUDA support in the cuda plugin inside of hwloc.
Our systems rely on dlopen, and don't have libltdl installed by default.
We're currently using a somewhat hacky / hardcoded patched version of hwloc that calls dlopen instead of libltdl.  It would be much nicer to have Open MPI's framework for this instead.
Unfortunately we don't have time right now to prepare this for upstream, but we wanted to open the Issue to get people thinking about it (and perhaps porting the Open MPI framework is easier than I understand?)

**Comment by bgoglin** [comment]
Candidates patches on top of git master https://github.com/bgoglin/hwloc/commits/dlopen

Waiting for IBM to test the v1.11 backport at https://github.com/bgoglin/hwloc/commits/v1.11-dlopen before actually merging to master. Tarball at https://ci.inria.fr/hwloc/job/zbgoglin-0-tarball/376/artifact/hwloc-v1.11-dlopen-20180330.1727.git320392d.tar.gz but it may disappear from the queue at some point.

**Comment by bgoglin** [comment]
@gpaulsen @jsquyres I discovered recently that OMPI doesn't use libltdl anymore unless dlopen is broken. Do you think we should do the same in hwloc? How do you know dlopen doesn't work? Configure-time test? or hardwired OS blacklisting? I couldn't find the relevant changes in the OMPI git log.

**Comment by jsquyres** [comment]
It's not so much that OMPI chooses ltdl "when dlopen is broken", but more like "when dlopen isn't available".  It's basically a simple test: if `dlopen` is available, prefer that.  [We have the `dl` framework for that nowadays](https://github.com/open-mpi/ompi/commit/e81c070ef0f68f9c1e8979cde20a26f622922198).  There's only two components:

1. `dlopen`: https://github.com/open-mpi/ompi/blob/master/opal/mca/dl/dlopen/configure.m4 does the usual `OPAL_CHECK_PACKAGE` m4 macro to look for `dlfcn.h`, `-ldl`, and the `dlopen` symbol.  
2. `libltdl`: https://github.com/open-mpi/ompi/blob/master/opal/mca/dl/libltdl/configure.m4 does a similar thing, but looks for `ltdl.h`, `-lltdl`, and `lt_dlopen`.

The `dlopen` component has a higher precedence than the `libltdl` component, so if the `dlopen` component `configure.m4` succeeds, that component is used and the `libltdl` component is ignored.  In short, we assume that the `dlopen` component is used pretty much everywhere; we made the `libltdl` component mostly as a fallback for any corner cases we didn't think of.

If you go back to the PR that contains https://github.com/open-mpi/ompi/commit/e81c070ef0f68f9c1e8979cde20a26f622922198 (i.e., https://github.com/open-mpi/ompi/pull/410) and spelunk backwards to see what issues / PRs led up to that point, it looks like it was a complicated (yet subtle) set of things that led us to the final solution of a `dl` framework with two components.  We _may_ have even brought up the libltdl issue on the libltdl mailing list at the time...?  (I didn't go back and look for that)

The end result is:

* Libltdl was written at a time when portably opening DSOs was a nightmare.  Libltdl did it correctly on a wide variety of platforms.
* Since then, `dlopen()` has become standardized on most (all?) platforms that Open MPI supports.  Hence, the need for `libltdl` is dramatically reduced.
* So Open MPI just "prefers" plain ol' `dlopen()` to the libltdl library.  This tends to avoid whatever corner case we experienced back then (that caused us to write the `dl` framework).

That being said, I think there may have been some (significant?) time lapse before we discovered whatever the specific libltdl problem was and writing the `dl` framework.  I think it was due to the fact that we didn't realize that `dlopen()` was standardized most everywhere we cared about, and really wasn't that hard to a) create the `dl` framework, and b) just use `dlopen()` in most cases.

**Comment by gpaulsen** [comment]
Wow, Thanks for closing.  I'd forgotten about this.
