### ISSUE TITLE
linker issue with libOpenCL.so

### ISSUE THREAD

**Issue by akshit-sharma** [open-mpi/hwloc#301]
### Which operating system and hardware are you running on?

* Linux 4.13.0-38-generic Ubuntu

### Details of the problem
Having linker issue with libOpenCL.so

### First approach
I am unable to compile hwloc from source (commit 33f0cee24d51ff37eb5d37cd82e2cd76665633ac).
Steps followed : 
$ git clone https://github.com/open-mpi/hwloc.git 
$ cd hwloc
$ ./autogen.sh
$ ./configure --prefix=...
$ make

gives a bunch of opencl linker errors
undefined reference to `clGetDeviceIDs@OPENCL_1.0`
undefined reference to `clGetPlatformIDs@OPENCL_1.0` 
undefined reference to `clGetPlatformInfo@OPENCL_1.0`
undefined reference to `clGetDeviceInfo@OPENCL_1.0`

### Alternative approach
I also tried using the [hwloc-2.0.1.tar.gz](https://www.open-mpi.org/software/hwloc/v2.0/downloads/hwloc-2.0.1.tar.gz). This one compiles and generates lstopo which is working but I am unable to compile the following cpp code with this.
Steps followed : 
Extracting the archive
$ ./configure --prefix=...
$ make 
$ make install

$./lstopo --version
./lstopo: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/akshit/Libraries/hwloc-2.0.1/lib/libhwloc.so.15)
lstopo 2.0.1

Then I tried a simple hello world code.
```c_cpp
#include <hwloc.h>
#include <stdio.h>

int main(int argc, char** argv) {
    hwloc_topology_t topology;
    int ncores;

    hwloc_topology_init(&topology);
    hwloc_topology_load(topology);
    ncores = hwloc_get_nbobjs_by_type(topology, HWLOC_OBJ_CORE);

    printf("Number of cores: %d\n", ncores);
    hwloc_topology_destroy(topology);

    return 0;
}
```

Compiling this program with the compiled extracted version gives the same error
g++    -c -o main.o main.cpp
g++ -o tests main.o -L/home/akshit/Libraries/hwloc-2.0.1-build/lib -lhwloc -lstdc++
/home/akshit/Libraries/hwloc-2.0.1-build/lib/libhwloc.so: undefined reference to `clGetDeviceIDs@OPENCL_1.0`
/home/akshit/Libraries/hwloc-2.0.1-build/lib/libhwloc.so: undefined reference to `clGetPlatformIDs@OPENCL_1.0`
/home/akshit/Libraries/hwloc-2.0.1-build/lib/libhwloc.so: undefined reference to `clGetPlatformInfo@OPENCL_1.0`
/home/akshit/Libraries/hwloc-2.0.1-build/lib/libhwloc.so: undefined reference to `clGetDeviceInfo@OPENCL_1.0`
collect2: error: ld returned 1 exit status

### Additional Information 
I have libOpenCL..so in two locations: 
/usr/local/cuda-8.0/lib64/libOpenCL.so 
/usr/lib/x86_64-linux-gnu/libOpenCL.so

And my LD_LIBRARY_PATH have /usr/local/cuda-8.0/extras/CUPTI/lib64:/usr/local/cuda-8.0/lib64

Can you help with this OpenCL error ?

Thanks

**Comment by bgoglin** [comment]
Hello

The mix of 2 libOpenCL.so might be the issue here. They could be defining OPENCL_1.0 symbols in one case and not in the other. Removing your envvar that point to /usr/local/cuda-8.0/ might confirm this (or chmod 0 /usr/local/cuda-8.0/lib64/libOpenCL.so).

Anyway, do you have other environment variables such as C_INCLUDE_PATH and LIBRARY_PATH pointing to the cuda directories too? Can you post your config.log or the output of configure that looks for OpenCL?

Your custom program likely needs a -lOpenCL on the g++ command line.

As a workaround, you should be to use --disable-opencl
Going back to hwloc 2.0.0 or 1.11.9 might also help because OpenCL was only enabled when AMD extensions are defined (which doesn't seem to be the case in CUDA8 OpenCL headers).

**Comment by akshit-sharma** [comment]
For some reason its compiling with `g++ -o tests main.o -lhwloc -lstdc++`.
Maybe my shared library is somewhere else than /home/akshit/Libraries/hwloc-2.0.1-build/lib.

Thanks for the reply though. -lOpenCL help me take this path.
