### ISSUE TITLE
Segmentation fault with netloc_ib_extract_dats

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [open-mpi/hwloc#304]
I am using hwloc-2.0.0 and building it with netloc enabled. When I run netloc_ib_extract_dats with the attached ib-raw input, I end up with a segmentation fault.
[ib-raw.tar.gz](https://github.com/open-mpi/hwloc/files/1895517/ib-raw.tar.gz)

Backtrace:
`#0  0x00007ffff7091faf in __strlen_sse42 () from /lib64/libc.so.6
#1  0x0000000000403140 in build_paths () at ../../../../hwloc-2.0.0/utils/netloc/infiniband/netloc_ib_extract_dats.c:280
#2  0x0000000000401352 in main (argc=<optimized out>, argv=<optimized out>) at ../../../../hwloc-2.0.0/utils/netloc/infiniband/netloc_ib_extract_dats.c:579`

**Comment by cbordage** [comment]
There is a bug when there is a missing port in the data.
Since Netloc won't give you helpful information about routes, you can remove your _ibroutes_ directory and everything. It should work.

I tried to draw your network, and the precomputed version is not good, so you have to move your nodes manually. Or you can use _netloc_draw.html_ from commit bb3393d.

Next month there will be a new version of Netloc with a lot of modifications with all that fixed.

**Comment by KavithaTipturMadhu** [comment]
Great, thanks.
