### ISSUE TITLE
Numa objects not returned when package and numa are at the same level

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [open-mpi/hwloc#312]
I am using hwloc version 2.0. When I call hwloc_get_ancestor_obj_by_type with type `HWLOC_OBJ_NUMANODE`  and an object of type HWLOC_OBJ_PU, I end up with root object. This is in case where package and NUMA  objects are at the same level.

**Comment by bgoglin** [comment]
That's expected in 2.0. NUMA nodes have moved away from the CPU hierarchy, they are attached as memory children. Hence, they are not ancestors of PU anymore, they are additional leaves on the side of PU and others. See https://www.open-mpi.org/projects/hwloc/doc/v2.0.1/a00327.php#upgrade_to_api_2x_memory_find

I can add a note to the doc saying that get_ancestor_by_depth/type don't work on PU and NUMA, but I can't make it work in this case since they are not ancestors anymore.

The second example in the link above is also an easy way to find local NUMA nodes (look at the current object nodeset, it contains one bit per local NUMA node os_index).
