### ISSUE TITLE
rpmbuild :: 2.0.3 :: tests fail

### ISSUE THREAD

**Issue by adriansev** [open-mpi/hwloc#350]
Trying to build rpm of hwloc 2.0.3 all tests fail because the newly built library is not found in /usr/lib64
but it is  located at that pre-packaging time in $RPM_BUILD_ROOT/usr/lib64
Any idea how can make this work?

**Comment by bgoglin** [comment]
That's strange. make check (assuming that's what you called tests) doesn't use the lib inside /usr/lib*, it uses the lib from the *build* directory (under hwloc/.libs or something like this). Libtool automatically takes care of this because each test program is actually a libtool wrapper script that points to the right lib and binary under .libs.

Can you give more details about how you built and ran tests?

**Comment by adriansev** [comment]
well, i took the spec file from [rpmfind](https://rpmfind.net/linux/RPM/centos/7.6.1810/x86_64/Packages/hwloc-1.11.8-4.el7.x86_64.html)
i disabled the patch and adapted the source name.
and make check does not use the lib from build directory :   
if i do a 'make check' in build directory all test fail but if i do 'LD_LIBRARY_PATH=${PWD}/hwloc/.libs make check' all tests are green   
(but on fedora have an error '/usr/bin/ld: hwloc-hello-cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC')

**Comment by bgoglin** [comment]
I don't know much about rpm specs file, but:

* There are also some lines that modify the libtool script. I guess it's related to the issue.
* at least you need to update lines the spec lines refering to the "src/" directory since it got renamed to "hwloc/" instead. Looks like only this line matters:
```
%check
LD_LIBRARY_PATH=$PWD/src/.libs make check
```

**Comment by adriansev** [comment]
Thanks! indeed this was the problem, and not all tests are green ... 
now i have to solve '/usr/bin/ld: hwloc-hello-cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC' but this is another issue
