### ISSUE TITLE
Embedded mode does not create shared library

### ISSUE THREAD

**Issue by matthiasdiener** [open-mpi/hwloc#371]
### What version of hwloc are you using?

2.1

### Which operating system and hardware are you running on?

Darwin, Linux

### Details of the problem

When building hwloc with `./configure --enable-embedded-mode --enable-shared=yes`, no shared library is built, only the static library. Furthermore, there appears to be no warning message that indicates that this is an unsupported configuration. Package authors that want to embed hwloc need to use error-prone workarounds to enable building the shared library (e.g. https://github.com/UIUC-PPL/charm/issues/2599).

**Comment by bgoglin** [comment]
@jsquyres Do you see a good reason not to support this?

**Comment by jsquyres** [comment]
What's the use case for wanting a shared library in embedded mode?

The intent with embedded mode was to give you only a static library so that when you linked it into whatever you're embedding hwloc in, it's fully "slurped in" to the enclosing library and/or application.

**Comment by matthiasdiener** [comment]
Our intent was to allow Charm++ applications to link to the embedded shared library for consistency in the linking process as well as to reduce binary size. We use a custom symbol prefix and are therefore not able to use the system hwloc.

**Comment by jsquyres** [comment]
Hmm.  I don't think I understand your use case.

> Our intent was to allow Charm++ applications to link to the embedded shared library for consistency in the linking process

But you said you use a custom symbol prefix.  Are you going to tell applications to use the internal Charm++ hwloc symbol prefix?  If so, that doesn't seem like a good idea.

> ...as well as to reduce binary size.

Reduce the binary size of what?  The Charm++ library, or the final application?  Is the Charm++ library a shared library?  If so, then the (static) hwloc library should be slurped up into that, and therefore the final linked application file size won't be affected.  If the Charm++ library is static, then your final linked application file size will include the hwloc library anyway.

So I'm not sure what you meant by this statement.  Are you worried about the size of the Charm++ library?  If so, I'm not sure it matters -- the linker will need to load in all the hwloc code, regardless of whether it is in the Charm++ library or a second standalone hwloc shared library.

> We use a custom symbol prefix and are therefore not able to use the system hwloc.

I'm not sure how to parse this.

Most use cases of prefixing the hwloc symbols are so that the hwloc library can be 100% internal/private.  If that's the case here, then I parse your statement as "We prefixed the symbols so that we could use the internal/private hwloc, and therefore we can't use the system hwloc."  If that's a correct parsing, then that's a _choice_ on your part (i.e., you _chose_ to prefix your hwloc symbols, and you could choose to _unprefix_ those symbols, too).

Can you explain in a bit more detail what you're trying to do?

**Comment by matthiasdiener** [comment]
I'll try to clarify.

> Hmm. I don't think I understand your use case.
> 
> > Our intent was to allow Charm++ applications to link to the embedded shared library for consistency in the linking process
> 
> But you said you use a custom symbol prefix. Are you going to tell applications to use the internal Charm++ hwloc symbol prefix? If so, that doesn't seem like a good idea.

No, Charm++ applications aren't really supposed to use the internal hwloc.

The intent was to link applications against the Charm++ libraries as well as our internal hwloc in the same way, ie. all libraries linked to are shared libraries or all are static libraries.

> 
> > ...as well as to reduce binary size.
> 
> Reduce the binary size of what? The Charm++ library, or the final application? Is the Charm++ library a shared library? If so, then the (static) hwloc library should be slurped up into that, and therefore the final linked application file size won't be affected. If the Charm++ library is static, then your final linked application file size will include the hwloc library anyway.

The Charm++ libraries and our internal hwloc library are always separate files, whether in the shared or static case. The goal is to allow a Charm++ application to dynamically link against all libraries, reducing the size of the binary.

> 
> So I'm not sure what you meant by this statement. Are you worried about the size of the Charm++ library? If so, I'm not sure it matters -- the linker will need to load in all the hwloc code, regardless of whether it is in the Charm++ library or a second standalone hwloc shared library.
> 

See above, we are not worried about the size of the Charm++ library.

> > We use a custom symbol prefix and are therefore not able to use the system hwloc.
> 
> I'm not sure how to parse this.
> 
> Most use cases of prefixing the hwloc symbols are so that the hwloc library can be 100% internal/private. If that's the case here, then I parse your statement as "We prefixed the symbols so that we could use the internal/private hwloc, and therefore we can't use the system hwloc." If that's a correct parsing, then that's a _choice_ on your part (i.e., you _chose_ to prefix your hwloc symbols, and you could choose to _unprefix_ those symbols, too).
> 
> Can you explain in a bit more detail what you're trying to do?

We need to support hardware topology on systems that don't have hwloc installed, which is why we chose to use an internal hwloc for Charm++. We prefixed the the symbols to avoid name clashes in case the Charm++ application itself intends to use the system hwloc (or their own hwloc) for their own needs.

**Comment by evan-charmworks** [comment]
Charm++ creates several different modular components as .so files that are linked in, partly for historical reasons. We currently poke a variable internal to hwloc's configure script so that it builds a shared library in embedded mode, described in [UIUC-PPL/charm#2599](https://github.com/UIUC-PPL/charm/issues/2599). Arguably this is not the best practice, and it results in a warning printed to stderr for everyone building Charm++.

This is the ldd output of a sample Charm++ application in this configuration:

```
$ ldd ./hello
	linux-vdso.so.1 (0x00007ffe64392000)
	libckmain.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libckmain.so (0x00007facc52fa000)
	libck.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libck.so (0x00007facc4b88000)
	libmemory-default.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libmemory-default.so (0x00007facc4984000)
	libthreads-default.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libthreads-default.so (0x00007facc477d000)
	libconv-machine.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libconv-machine.so (0x00007facc455e000)
	libconv-core.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libconv-core.so (0x00007facc42ec000)
	libtmgr.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libtmgr.so (0x00007facc40de000)
	libconv-util.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libconv-util.so (0x00007facc3e3b000)
	libconv-partition.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libconv-partition.so (0x00007facc3c39000)
	libhwloc_embedded.so.0 => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libhwloc_embedded.so.0 (0x00007facc39dc000)
	libcudart.so.9.1 => /usr/lib/x86_64-linux-gnu/libcudart.so.9.1 (0x00007facc376e000)
	libldb-rand.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libldb-rand.so (0x00007facc356a000)
	libconv-ldb.so => /home/evan/charm/netlrts-linux-x86_64-smp/lib_so/libconv-ldb.so (0x00007facc3328000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007facc2f9f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007facc2d87000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007facc2996000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007facc2779000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007facc23db000)
	/lib64/ld-linux-x86-64.so.2 (0x00007facc5710000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007facc21d7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007facc1fb8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007facc1db0000)
```

(For reference, my full Charm++ build line was `./build charm++ netlrts-linux-x86_64-smp -j8 --build-shared -g && cd netlrts-linux-x86_64-smp/tests/charm++/simplearrayhello && make OPTS="-g -charm-shared" -j8`.)

**Comment by jsquyres** [comment]
> The Charm++ libraries and our internal hwloc library are always separate files, whether in the shared or static case (we don't slurp hwloc into our libraries). The intent is to allow a Charm++ application to dynamically link against all libraries, reducing the size of the final binary.

Oh, I see the disconnect now.

We assume that if you embed hwloc, then you are slurping the generated static hwloc library into your own library (i.e., the Charm++ library).  I.e., we assume that you are not exposing the internal hwloc library to end applications.

Specifically: you can slurp up `libhwloc.a` into `libcharm++.so` or `libcharm++.a`.  That's why we only allow generating a static libhwloc -- because we assume you are slurping it into:

* an application, or
* a static library, or
* a dynamic library

> We need to support hardware topology on systems that don't have hwloc (or its development files) installed, which is why we chose to use an internal hwloc for Charm++. We prefixed the symbols to avoid name clashes in case a Charm++ application itself intends to use the system hwloc (or their own hwloc) for their own needs.

Yes, this is pretty much the canonical case for embedding hwloc.

**Comment by jsquyres** [comment]
> Charm++ creates several different modular components as .so files that are linked in, partly for historical reasons. We currently poke a variable internal to hwloc's configure script so that it builds a shared library in embedded mode, described in [UIUC-PPL/charm#2599](https://github.com/UIUC-PPL/charm/issues/2599). Arguably this is not the best practice for achieving our goal, and it results in a warning printed to stderr for everyone building Charm++.

If you can avoid doing that, that would be best.

I.e., just slurp `libhwloc_embedded.a` into some other Charm++ library, and you should be good to go.

Open MPI does this, for example.  The Automakemagic is a little convoluted because of Open MPI's configure-time detection of plugins, but it essentially happens here:

https://github.com/open-mpi/ompi/blob/6e3ff5e9b44ccbb49807d84998bafebc6ee3c9fc/opal/mca/hwloc/hwloc201/Makefile.am#L38-L45

The `LIBADD` line adds in `$(opal_hwloc_hwloc201_LIBS)`, which is defined in the output `Makefile` as:

```
opal_hwloc_hwloc201_LIBS = $(OPAL_TOP_BUILDDIR)/opal/mca/hwloc/hwloc201/hwloc/hwloc/libhwloc_embedded.la $(HWLOC_EMBEDDED_LIBS)
```

I.e., it's the absolute path to the generated `libhwloc_embedded.la` plus whatever else the hwloc configury told me it needed for dependencies (i.e., `$(HWLOC_EMBEDDED_LIBS)`).

Make sense?

**Comment by matthiasdiener** [comment]
> We assume that if you embed hwloc, then you are slurping the generated static hwloc library into your own library (i.e., the Charm++ library). I.e., we assume that you are not exposing the internal hwloc library to end applications.
> 
> Specifically: you can slurp up `libhwloc.a` into `libcharm++.so` or `libcharm++.a`. That's why we only allow generating a static libhwloc -- because we assume you are slurping it into:

But wouldn't we need different hwloc compilation options depending on whether we are adding hwloc to `libcharm++.so` or `libcharm++.a` (e.g., `-fpic` for .so)?

Out of curiosity, is there any technical restriction why embedded mode does not produce a shared library (even if explicitly requested)?

**Comment by jsquyres** [comment]
Everything @bgoglin said plus: the whole idea of embedded is to make an hwloc library that is slurped up into some other entity.  It is not intended to be a standalone library.  If you want a standalone library, then don't use embedded mode and you can control whether you generate a static or shared hwloc library.

Put differently: embedded = a libtool convenience library that is designed to be slurped up into something else.  And you can optionally prefix the hwloc symbols.

For your specific question:

> But wouldn't we need different hwloc compilation options depending on whether we are adding hwloc to libcharm++.so or libcharm++.a (e.g., -fpic for .so)?

If you're building with Automake/Libtool, I think that Libtool will just do the Right Things when creating your final `libcharm++.whatever`.  I.e., Libtool knows how to slurp convenience libraries into both static and dynamic libraries.

**Comment by matthiasdiener** [comment]
Ok, thank you for the information! I'd still suggest adding a warning or error message in case hwloc is configured with something like `./configure --enable-embedded-mode --enable-shared=yes`.

**Comment by bgoglin** [comment]
I was looking at adding that warning but it doesn't look easy unfortunately.

**Comment by jsquyres** [comment]
Yes, it gets tricky because the determination of shared / static may be from the top-level package, and not intended for hwloc. We have no idea which one the user intended to be static / shared. 

Hence hwloc‘s configure assumes that it is being used for its intended purpose: generate a Libtool convenience library, which isn’t affected by the CLI options for static / shared.

**Comment by matthiasdiener** [comment]
As an alternative, could you enable the optional prefix for the hwloc symbols in non-embedded mode?

**Comment by bgoglin** [comment]
@matthiasdiener You should pass --with-hwloc-symbol-prefix=foobar on the configure line to get foobarhwloc_ instead of hwloc_ as a prefix.

**Comment by evan-charmworks** [comment]
We've resolved this issue on our end, properly slurping all hwloc object files into our own library. This issue can be closed.

**Comment by bgoglin** [comment]
Good, thanks for letting us know!
