### ISSUE TITLE
please round PCIe link values

### ISSUE THREAD

**Issue by sthibaul** [open-mpi/hwloc#372]
From http://bugs.debian.org/946160 : 

Version: 2.1.0+dfsg-2

Dear Maintainer,

my system has a NVMe SSD.  It is displayed correctly in lstopo.  However the PCIe link has a value of "3.9" (see attached file) whereas it should probably be "4.0".
[lstopo.pdf](https://github.com/open-mpi/hwloc/files/3922474/lstopo.pdf)

**Comment by bgoglin** [comment]
Copy of what I sent to the Debian report:
"PCIe links (since Gen3) are encoded 128 data rate over 130 signal rate. That's why you get 3.93 (truncated to 3.9). We decided to keep that value exact in hwloc because the data/signal rate is different among PCIe generations. We could round it up to 4 in the lstopo output, but I am not sure where to start (PCIe Gen4 16x is 31.5GB/s instead of 32 and Gen5 will be 63 instead of 64, those are harder to round up)."
