### ISSUE TITLE
Is there a limitation that the initiator type is HWLOC_LOCATION_TYPE_CPUSET when getting HWLOC_MEMATTR_ID_BANDWIDTH?

### ISSUE THREAD

**Issue by keiya-nobuta** [open-mpi/hwloc#433]
I want to display all bandwidth combinations between NUMA node targets and initiators, I tested the following code:

```
    hwloc_obj_t init_node = NULL;
    while ((init_node = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_NUMANODE, init_node)) != NULL) {
        struct hwloc_location initiator;

        initiator.type = HWLOC_LOCATION_TYPE_OBJECT;
        initiator.location.object = init_node;

        hwloc_obj_t target = NULL;
        while ((target = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_NUMANODE, target)) != NULL) {
            hwloc_uint64_t value;
            err = hwloc_memattr_get_value(topology, HWLOC_MEMATTR_ID_BANDWIDTH, target, &initiator, 0, &value);
            if (err) continue;

            printf("  init[%u] to targ[%u] value=%lu\n", init_node->os_index, target->os_index, value);
        }
    }
```

but it didn't work (nothing was displayed).  After I changed initiator type to HWLOC_LOCATION_TYPE_CPUSET, then the values was displayed as intendeed. There is no problem in practical use, but I don't understand the difference.

```
-        initiator.type = HWLOC_LOCATION_TYPE_OBJECT;
-        initiator.location.object = init_node;
+        initiator.type = HWLOC_LOCATION_TYPE_CPUSET;
+        initiator.location.cpuset = init_node->cpuset;
```

using version:
- lstopo 2.4.0a1-git
- a3a68b48 (HEAD -> master) contrib/git-hooks: add a pre-commit hook template

testing emvironment:
Linux, emulated 2 of 4 NUMA nodes as non-cpu nodes by QEMU (see here: https://github.com/memkind/memkind/issues/383).

**Comment by bgoglin** [comment]
Hello.

The issue here is that a NUMA node is a vague concept. In the past, it was a CPU + its local memory. Nowadays it doesn't make much sense anymore because you may have different memories near the same CPU. Now we have initiators (CPUs) and targets (Memory). What hwloc now calls NUMA node is a target. It's not an initiator because a memory cannot read/write to other memories, while a CPU can. That's why TYPE_OBJECT does nothing above.

TYPE_OBJECT is basically unused now. It may be used in the future if we ever describe the performance when an initiator is a GPU, but right now all initiators are CPUs, better described as cpuset.

There was some idea of auto converting some object (e.g. a PU or Core) to cpusets internally when TYPE_OBJECT is passed but I didn't want to make things too difficult to explain in the doc.

I'll try to better document this.

**Comment by keiya-nobuta** [comment]
Thank you very much for all the details.
