### ISSUE TITLE
HWLOC API to bind shared memory between two processes to a numa node

### ISSUE THREAD

**Issue by rppendya** [open-mpi/hwloc#509]
In linux, there is set_mempolicy() and mbind() that would allow shared memory between two processes to bind to a numa node. I read hwloc documentation to see if there is any API that would allow binding shared memory to a numa node and I didn't find one. 
Is there any such API in HWLOC and can you please point it to me?

**Comment by bgoglin** [comment]
Hello. Te existing API would work fine. Linux shared memory isn't different from "normal non-shared" memory, it can become shared at any time or become non-shared when processes unmap/exit. hwloc uses set_mempolicy() and mbind() internally, it should just work. If there's anything to clarify in the doc, please let me know.

**Comment by rppendya** [comment]
Thanks Brice. I should be able to use hwloc_set_membind() then. I checked the actual code of this API in hwloc. Looks like, in linux membind is per thread only and not for the entire process. In topology-linux.c, I only see callback function for set_thisthread_membind() and nothing for set_thisproc_membind(). 

Will hwloc_set_membind() work on windows too?

**Comment by bgoglin** [comment]
Linux only allows to set per thread membind policy, and only for the current thread. Thus we can't even iterate over all threads of a process to change the policy for all of them (what we do for process CPU binding). That's why there's no set_thisproc_membind() on Linux.
set_membind() on Windows should work, although I didn't test it recently. It's basically identical to set_cpubind() since CPU and memory binding are linked on Windows.
I am closing this issue but feel free to ask more questions here if needed.
