### ISSUE TITLE
enable CUDA/ROCm when not in LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#515]
Since hwloc 2.5, we autodetect CUDA in /usr/local/cuda. Since 2.6, we also autodetect ROCm under /opt/rocm. And we support custom path with --with-cuda=... --with-rocm=... It works fine but causes our library to depend on NVIDIA/AMD libraries that are not always in LD_LIBRARY_PATH or ld.so.conf.

The CUDA installer seems to install /etc/ld.so.conf.d/cuda-x.conf at least on CentOS but some platforms don't have it, causing end-users to get unexpected mpirun failures because it couldn't find some NVIDIA lib, e.g. ompi#9907 on Amazon EC2

It's quite common to support --with-foo=/my/path/that's/not/in/LD_LIBRARY_PATH so I don't think we're doing anything wrong, but maybe there's a way to warn users that we're enabling something that will require LD_LIBRARY_PATH? May require AC_RUN_IFELSE().

Or maybe people use rpath to hardwire the path of those dependencies?

**Comment by jjhursey** [comment]
We have a build/run container environment that we maintain for Open MPI/OpenPMIx/PRRTE CI. It has CUDA installed, but the library `libnvidia-ml.so.1` is missing (we have the stub in `/usr/local/cuda-11.0/targets/ppc64le-linux/lib/stubs/libnvidia-ml.so`). On the host system the true library is located in `/usr/lib64/`, but in the container it does not. I suspect because we are not using the nvidia container runtime on this machine, but that's somewhat beside the point.

The hwloc `config.log` reports:
```
configure:26463: checking for nvmlInit in -lnvidia-ml
configure:26488: gcc -o conftest -g -O2  -I/usr/local/cuda/include/  -L/usr/local/cuda/lib64/ -L/usr/local/cuda/lib64/stubs/ conftest.c -lnvidia-ml   >&5
configure:26488: $? = 0
configure:26497: result: yes
```

But when I run it shows this error message:
```
shell$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs/                         
shell$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/      
shell$ lstopo
lstopo: error while loading shared libraries: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
```

I think the configure check just needs to be stronger. Since I can reproduce, I'm happy to take a deeper look at it. I might not be today, but I'll try to get to it early this week.

**Comment by rhc54** [comment]
@rhc54 Just tagging myself so I can follow along.

**Comment by bgoglin** [comment]
I have seen the issue with libnvidia-ml.so.1 missing, I seem to remember it's packaged by the NVIDIA driver while the .so is in the CUDA toolkit, or something like this? Basically NVIDIA wants you to build but not to run unless the driver is installed. It makes sense when you have a frontend node for compiling without the driver, and compute nodes for executing with the driver. But in your case, it's completely different. I need to check again if I remember things correctly.

How would you make the configure check stronger? AC_RUN_IFELSE() or is there another way?

**Comment by jjhursey** [comment]
Pretty much. Linking is successful, but running is not. So we need a run of the resulting `conftest` to decide if we can use that feature or not.

I am working on something like:
```
if( linking successful ) {
  // Add a configure option for the user to skip the running check
  // if they happen to know that this is ok (building on a node without
  // the cuda driver, but plan to run only on a system with it.
  if( check_runtime_cuda && running is not successful ) {
    happy = no
  } else {
    happy = yes
  }
}
```

**Comment by rhc54** [comment]
I don't think that is going to work, I'm afraid - the problem is that `mpirun` itself needs to load `hwloc`, and `mpirun` typically runs on the login node (and not the backend) where GPUs typically are not found. This is normally not a problem as hwloc had minimal dependencies, none of which were "backend only" in nature.

I'm beginning to think that the only real solution might be to return hwloc to being a plugin so that it can fail without impact. Negative is that we will go back to "flooding" the IO gateways with hwloc library loads, which is what we have been trying to get away from doing. So it could be that we have to go this way, but tell people with big machines that they (a) need to ensure the nvidia libraries are installed everywhere, and (b) configure/build OMPI, PMIx, and PRRTE with `--disable-dlopen`.

**Comment by rhc54** [comment]
Or are you just going to disable CUDA completely when building hwloc in that scenario? That would seem a shame as you lose some level of support by doing so.

**Comment by jjhursey** [comment]
Now that PR #516 is merged are we able to close this issue?

**Comment by bgoglin** [comment]
The original issue was rather that a library exists but is not in ld.so.conf or LD_LIBRARY_PATH. hwloc knows where to look for default install directories (/opt/rocm and /usr/local/cuda) but those paths aren't known to the dynamic linker when launching the program. It's different from your libnvidia-ml.so case where the library doesn't exist at all.

NVIDIA seems to say that setting LD_LIBRARY_PATH manually is mandatory in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#mandatory-post and it looks like distro packagers actually do it in ld.so.conf. The problem shouldn't be very common, but I think that's what happened on EC2.

AMD isn't so clear in the ROCm doc https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#post-install-actions-and-verification-process and it doesn't seem to be done on the only AMD platform I could test.

Adding something like --enable-rpath for CUDA and ROCm libs might be useful for those cases. I'd like to be able to detect whenever we link NVIDIA or ROCm libs in non-standard path (need to define what this means), warn that ld.so.conf or LD_LIBRARY_PATH may be needed, and note that --enable-rpath might help too. But there are so many cases that it's not easy to implement (--with-cuda, pkg-config, CUDA_VERSION, /usr/local/cuda, ...).

**Comment by bgoglin** [comment]
Actually, just like you did for NVML, we could AC_RUN_IFELSE() for cudaGetDeviceCount() (in <cuda_runtime_api.h>) and rsmi_init() (in <rocm_smi/rocm_smi.h>) to detect missing LD_LIBRARY_PATH/ld.so.conf

**Comment by rhc54** [comment]
I wonder - is there some way we (i.e., PMIx/PRRTE) could detect that HWLOC was built with CUDA support, then check for the dependent libraries? I'm not sure how to completely solve the "missing lib" problem, but it would be really nice if we could at least detect that the problem existed and output a nice error message (perhaps instructing the user on how to fix it) as opposed to just getting the loader's "missing -lnvidia" and abort.

I have demonstrated I can do it by moving hwloc back into a plugin (and re-enabling dso for it), but that also has consequences. I need to noodle over those a bit to their impact - will come back with some further thoughts later.

**Comment by bgoglin** [comment]
If you want to know when CUDA support is built *inside* hwloc (as opposed to built as a separate plugin) I should be able to add some #define HWLOC_CUDA_BUILTIN (one for each optional component).

**Comment by bgoglin** [comment]
Here's what I can get in the public hwloc/autogen/config.h (auto-included in hwloc.h) when CUDA/NVML/RSMI are disabled, LevelZero is enabled but plugin, and PCI/OpenCL/GL/libxml are enabled and built statically inside hwloc:
```
#define HWLOC_PCI_COMPONENT_BUILTIN 1
#define HWLOC_OPENCL_COMPONENT_BUILTIN 1
/* #undef HWLOC_CUDA_COMPONENT_BUILTIN */
/* #undef HWLOC_NVML_COMPONENT_BUILTIN */
/* #undef HWLOC_RSMI_COMPONENT_BUILTIN */
/* #undef HWLOC_LEVELZERO_COMPONENT_BUILTIN */
#define HWLOC_GL_COMPONENT_BUILTIN 1
#define HWLOC_XML_LIBXML_COMPONENT_BUILTIN 1
```

**Comment by bgoglin** [comment]
And I can warn like this when AMD ROCm isn't in LD_LIBRARY_PATH/ld.so.conf:
```
config.status: executing chmoding-scripts commands

************************************************************************
WARNING: AMD ROCm SMI was detected but programs linked against it cannot
run. This often indicates that the ROCm SMI lib path is missing in
ld.so.conf and LD_LIBRARY_PATH. If unneeded, this dependency may be
removed from hwloc by passing --disable-rsmi to configure.
************************************************************************

-----------------------------------------------------------------------------
Hwloc optional build support status (more details can be found above):

Probe / display I/O devices: PCI(linux) LinuxIO OpenCL CUDA RSMI
ROCm SMI status:             yes, but not in LD_LIBRARY_PATH or ld.so.conf (see warning above)
Graphical output:            no
XML input / output:          basic
Netloc functionality:        yes (without scotch)
Plugin support:              no
-----------------------------------------------------------------------------

```
The detection is the same for NVML but the warning is different. I'd do the same for CUDA.

**Comment by rhc54** [comment]
Looping in @jsquyres and @bwbarrett so we don't go down into the weeds

While I think the configure-time check improvement and warnings are good, my concerns are:

(a) many sys admins I've known simply run a script to update/install a package like HWLOC and will never see the warning 
(b) even if they do, once deployed the user will never see it
(c) most organizations install via rpm, which means they will never see the warning

Thus, while it is a step forward, it really doesn't address the problem we originally cited. The user will still see "mpirun" fail and only get a cryptic "cannot find -lnvidia" error from the loader. I suspect I won't be alone in having no idea what that means or where it is coming from since it is a "hidden" dependency a couple of layers down from what I am executing.

I don't know how to solve the underlying problem. My primary objective at this point is simply to provide the user with an error message better than "cannot find -lnvidia" so they at least have _some_ idea of what to do. However, both of my solutions require that we utilize plugins (either in HWLOC or PMIx/PRRTE) so we can gracefully fail to load the plugin, and if we know HWLOC was built with NVML (or ROCm), then generate a helpful message.

The problem with the plugin approach is the impact on launch scaling on larger machines - i.e., the dreaded "plugin loading" storm. What I don't know (and perhaps others do) is if we can:

(a) point HWLOC at a local location where the required library should reside
(b) restrict the loader to _only_ look in that location - i.e., to not hit the IO subsystem if the library isn't where we pointed

@jsquyres @bwbarrett You guys know more about loaders than I do - are these steps possible? If so, how do we implement them? Or is there a non-plugin way we can detect that the library isn't available pre-loader so we can gracefully (and informatively) error out?

**Comment by bgoglin** [comment]
Before spending more time on this, I really need to know what has been observed so far. I've seen a missing libOpenCL.so on AWS only so far (ompi#9907), and it may just be CUDA not correctly installed as explained in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#mandatory-post
That's clearly not enough to spend hours on this. What did you ever see?

(a) libnvidia-ml.so.1 missing on login
(b) libcudart.so.X or libOpenCL.so.Y not found because of LD_LIBRARY_PATH/ld.so.conf incorrect
(c) anything else?
(A) on production clusters => doesn't seem widely affected since Debian-based distros didn't report anything, spack looks fine too, NVIDIA RPMs install a ld.so.conf.d file, etc.
(B) for CI envrionment, containers, ... => OMPI developers will see the failure and apply the NVIDIA mandatory steps (ld.so.conf), problem solved
(1) internal hwloc
(2) external hwloc

For nvidia-ml/internal (a)+(1), just disable nvml in OMPI's hwloc build since you don't need it.
For cuda/internal (b)+(1), we may add --enable-rpath to hwloc so that OMPI knows where to find hwloc dependencies if the admin really doesn't want do install CUDA correctly.

For external cases (2), the hwloc install is broken, the sysadmin or distro packager didn't even test lstopo after building hwloc. Getting a user report is the best way to get him to read the new hwloc warnings and fix his install.

I know that's rude, but there's no readon to spend more time unless I get proof of the problem existing for real in the wild.

**Comment by bwbarrett** [comment]
Note that https://github.com/open-mpi/ompi/issues/9907 is a real issue, but one where HWLOC's plugins are the right option.  In that case, OMPI was built (using internal libevent, hwloc, pmix, prrte) on the AWS EFA team's build server, which has the entire CUDA stack properly installed.  Those HWLOC/PMIX/PRRTE/etc. build artifacts were then used on instance B, which did not have any CUDA bits on it.  OMPI traditionally has worked hard to make this situation work properly (by just not running CUDA bits, because that plugin doesn't load).  Defaulting to adding `--enable-plugins` when building internal HWLOC solved that problem.

It sounds like Josh found a couple of configure issues for some of the corner cases they've run into, and we definitely did have some problem figuring out the right incantation of configure arguments to get HWLOC to not build CUDA support when the CUDA libraries were available (as a workaround until we sorted out the plugin thing), but I'm not sure those are as high priority as OMPI building with plugins.

**Comment by bgoglin** [comment]
configure arguments are likely complicated because CUDA installs libcuda and libopencl (and maybe libnvidia-ml, not sure) in the same directory. hwloc basically finds that directory and then enables everything found in there. If you disable cuda, it'll still find opencl. So you need disable all of them (cuda, opencl, nvml iirc).

--with-cuda=/nonexisting helps because it changes the default CUDA directory, which is where OpenCL/... are found. We could add a configure option to disable the entire NVIDIA stack, or rename options, etc to make things more clear.

**Comment by bwbarrett** [comment]
Or document the `--with-cuda=/nonexisting` hack.  Any of those seems fine, although we should probably have that discussion separate from this thread :).

**Comment by bgoglin** [comment]
I am closing this issue since it mixes too many different problems. We have several warnings in configure now, I documented the --with-cuda=/nonexisting, and I moved the --enable-rpath idea alone in #518.
