### ISSUE TITLE
Error undefined symbol: hwloc_cpukinds_get_nr

### ISSUE THREAD

**Issue by coderodyhpc** [open-mpi/hwloc#527]
Hello,
I've installed 2.7.1 from the tar file on an Ubuntu 20.04 system. Everything seems to be there but I'm getting the message:
```
$ lstopo
lstopo: symbol lookup error: lstopo: undefined symbol: hwloc_cpukinds_get_nr
Also, I checked for any hwloc_cpukinds_get_nr file or reference and got:
/usr$ grep -r "hwloc_cpukinds_get_nr" *
Binary file bin/hwloc-info matches
Binary file bin/hwloc-calc matches
Binary file bin/lstopo matches
Binary file bin/lstopo-no-graphics matches
include/hwloc/cpukinds.h: * The number of kinds may be obtained with hwloc_cpukinds_get_nr().
include/hwloc/cpukinds.h:hwloc_cpukinds_get_nr(hwloc_topology_t topology,
include/hwloc/cpukinds.h: * of kinds returned by hwloc_cpukinds_get_nr() minus 1.
include/hwloc/cpukinds.h: * (as reported by hwloc_cpukinds_get_nr()) minus 1.
include/hwloc/rename.h:#define hwloc_cpukinds_get_nr HWLOC_NAME(cpukinds_get_nr)
Binary file lib/libhwloc.so.15.5.3 matches
```
Thanks.

**Comment by bgoglin** [comment]
Hello.
Run "ldd /usr/bin/lstopo" to check which version it uses. I guess it uses an older libhwloc which doesn't contain hwloc_cpukinds_get_nr. Ubuntu may have one /usr/lib/x86_64-linux-gnu/ (if some package ever required libhwloc) and that one may take precedence over yours in /usr/lib
Usually you don't install manually-built things in /usr but rather in /usr/local, or /opt, because /usr already contains what official packages bring.
By the way, hwloc 2.7.1 is already in Debian, hence it'll be in Ubuntu soon.

**Comment by coderodyhpc** [comment]
Hello @**bgoglin**,
The error went away after reconfiguring with `--libdir=/usr/lib/x86_64-linux-gnu`. It's now complaining about not finding the NVIDIA management library 
`hwloc/nvml: Failed to initialize with nvmlInit(): Driver Not Loaded`
I'm unsure if having the NVIDIA drivers is now sort of mandatory but it probably doesn't interfere with hwloc running on CPU-only systems. 
Thanks.

**Comment by bgoglin** [comment]
NVIDIA drivers aren't mandatory and will never be. But if you have nvml installed, hwloc will detect it and try to use it. You may disable at configure time with --disable-nvml.
I am closing this issue but feel free to ask more questions here if any.

**Comment by coderodyhpc** [comment]
Thanks!
