### ISSUE TITLE
does Hwloc has a mechanism to read CDAT/HMAT table for NUMA/CXL devices (specifically Bandwidth/latency matrix between targets and initators) ?

### ISSUE THREAD

**Issue by aghozzo** [open-mpi/hwloc#586]
If the answer is NO, 
- is there a plan to expose this info in Sysfs in user space or any other way? 
- Is it a complicated job to read and expose these tables ? 

Thanks

**Comment by bgoglin** [comment]
Hello
HMAT and CDAT tables are directly only exposed to root in /sys, but they are not accessible to non-root users. However most of their contents is exposed in specific sysfs files that hwloc already reads (/sys/devices/system/node/nodeX/accessX/...). However, for CXL nodes, this is only planned for 6.5 afaik, some kernel patches are currently under review.
The big missing thing is that only best initiator performance is exposed in system, other values are not.
Brice

**Comment by aghozzo** [comment]
Thanks for the reply, I have more questions if ok. 

1- Can you give an example of how to read the tables as root in /sys  
2-  can you please elaborate on "best initiator"?  is "best" based on Bandwidth or latency ? do you supply a target and it gives you best initiator ? i was thinking its the other ay around, you decide on where you running in the system and you ask what is the best target for me ?

**Comment by bgoglin** [comment]
HMAT is with other ACPI tables under /sys/firmware/acpi/tables/
CDAT is under the CXL endpoint directory, for instance /sys/devices/platform/ACPI0017:00/root0/port1/port2/port5/endpoint8/CDAT

IIRC best is based on write latency first, then read lat, then write BW, then read BW. You get that best initiator for each NUMA node (memory target). It's really not perfect but it's not so bad on current and upcoming platforms. Each target (let's say DRAM, HBM and CXL) is local to some CPUs, which is set to its best initiator. So when you want to find the best target for some CPUs, you iterate over their local target NUMA nodes (local DRAM, HBM and CXL), compare performance for these initiator-target pairs, and you get your best target (that's what hwloc_memattr_get_best_target() does internally). However, for more complex platforms, it's not clear it'll work well since a target could be the best for a given initiator without that initiator being the best for that target:

System where CPU0 accesses MEM2 at 100ns and MEM3 at 200ns, while CPU1 access MEM2 at 400ns and MEM3 at 300ns. CPU0 is the best initiator for both MEM2 and MEM3, but best target for CPU1 is MEM3 (not visible under current Linux kernels because CPU1 isn't the best initiator).

There's some doc under:
https://www.kernel.org/doc/Documentation/admin-guide/mm/numaperf.rst
(and drivers/acpi/numa/hmat.c in the kernel source).

**Comment by aghozzo** [comment]
Thanks for the information, appreciated

**Comment by aghozzo** [comment]
Hi, one more question if possible. 

The tables in /sys if root  (/sys/firmware/acpi/tables/HMAT) , whats the best way to read them in a useful format . how hwloc extract info from the tables ?

**Comment by bgoglin** [comment]
The "iasl" tool from the acpica-tools package (or something like that, depending on your Linux distribution) can convert the HMAT table from binary format (in /sys/firmware) to human-readable format. However the result is still difficult to read unless you have the ACPI specification of the HMAT table with you (available from https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#heterogeneous-memory-attribute-table-hmat). hwloc currently doesn't parse that table directly (because root only). It lets the kernel parse it and expose some info in /sys, then hwloc reads things from /sys (hence hwloc doesn't have all initiator-target values, as explained above).

You only get access0/access1 if the HMAT table is entirely filled, and maybe only if it specifies values that allow Linux to find a best initiator. Did you give all HMAT values to Qemu? I have an example at https://github.com/open-mpi/hwloc/wiki/Simulating-complex-memory-with-Qemu#hmat-performance-attributes

**Comment by aghozzo** [comment]
Thank you , your help is appreciated . will study the information and re-open if needed ,

**Comment by aghozzo** [comment]
Hi, 

As far as you know , is there any (Qemu release/ command run steps) that support CDAT and expose CXL devices bandwidth latency information ?

**Comment by bgoglin** [comment]
There's some support from end of 2022 so it might be in latest releases. This commit has a bit of doc:
```
commit f5ee7413d5928930604f73675fe89f21fbabc8b3
Author: Huai-Cheng Kuo <hchkuo@avery-design.com.tw>
Date:   Fri Oct 14 16:10:44 2022 +0100

    hw/mem/cxl-type3: Add CXL CDAT Data Object Exchange
    
    The CDAT can be specified in two ways. One is to add ",cdat=<filename>"
    in "-device cxl-type3"'s command option. The file is required to provide
    the whole CDAT table in binary mode. The other is to use the default
    that provides some 'reasonable' numbers based on type of memory and
    size.
    
    The DOE capability supporting CDAT is added to hw/mem/cxl_type3.c with
    capability offset 0x190. The config read/write to this capability range
    can be generated in the OS to request the CDAT data.
    
    Signed-off-by: Huai-Cheng Kuo <hchkuo@avery-design.com.tw>
    Signed-off-by: Chris Browy <cbrowy@avery-design.com>
    Signed-off-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
```
I never tested it, kernel support is still under development iirc.

**Comment by bgoglin** [comment]
I forgot to actually close :)
