### ISSUE TITLE
2.10.0-rc1 fails to build on various archs

### ISSUE THREAD

**Issue by sthibaul** [open-mpi/hwloc#637]
See https://buildd.debian.org/status/package.php?p=hwloc&suite=experimental and in particular at least https://buildd.debian.org/status/fetch.php?pkg=hwloc&arch=s390x&ver=2.10.0~rc1-1&stamp=1700580704&raw=0 https://buildd.debian.org/status/fetch.php?pkg=hwloc&arch=powerpc&ver=2.10.0~rc1-1&stamp=1700581275&raw=0  https://buildd.debian.org/status/fetch.php?pkg=hwloc&arch=ppc64&ver=2.10.0~rc1-1&stamp=1700580978&raw=0

So at least Debian linux s390x, Debian linux powerpc, and Debian linux ppc64. s390x is the most concerning since it's a Debian release arch.

**Comment by bgoglin** [comment]
I reproduced the issue on a ppc64 on cfarm. It's likely a endianness issue since these three architectures are big endian and I can't find/reproduce a failure on any little-endian architecture. I need to see how to hack the code to read DMI/SMBIOS fields as LE when running LE tests on BE.

**Comment by bgoglin** [comment]
@xiongzubiao Do you know if SMBIOS fields are stored in fixed order or depend on the platform endianness? This issue comes from your code reading the size and extended_size fields of the memory SMBIOS structure. Your code assumes the SMBIOS fields are stored using the endianness of the host CPU, which obviously fails in our strange test case (parsing SMBIOS fields from little-endian machine on a big-endian machine).

I can't find a clear answer about the order of bytes in SMBIOS fields. The specs only talks about endianness twice. The first one seems to say little-endian everywhere:
"NOTE The Entry Point Structure and all SMBIOS structures assume a little-endian ordering convention unless explicitly specified otherwise, such as multibyte numbers (WORD, DWORD, and so on). These structures are stored with the low-order byte at the lowest address and the high-order byte at the highest address."
However the other one seems to say network order everywhere except in the system UUID:
"Although RFC4122 recommends network byte order for all fields, the PC industry (including the ACPI,
UEFI, and Microsoft specifications) has consistently used little-endian byte encoding for the first three
fields: time_low, time_mid, time_hi_and_version. The same encoding, also known as wire format, should
also be used for the SMBIOS representation of the UUID."
I asked DMTF/SMBIOS about this but I am asking you too in case you know the answer.

**Comment by bgoglin** [comment]
From the dmidecode source code, it looks everything is LE. Size and extended_size are read using WORD() and DWORD() macros which are defined as:
```
/*
 * Per SMBIOS v2.8.0 and later, all structures assume a little-endian
 * ordering convention.
 */
#if defined(ALIGNMENT_WORKAROUND) || defined(BIGENDIAN)
#define WORD(x) (u16)((x)[0] + ((x)[1] << 8))
#define DWORD(x) (u32)((x)[0] + ((x)[1] << 8) + ((x)[2] << 16) + ((x)[3] << 24))
#define QWORD(x) (U64(DWORD(x), DWORD(x + 4)))
#else /* ALIGNMENT_WORKAROUND || BIGENDIAN */
#define WORD(x) (u16)(*(const u16 *)(x))
#define DWORD(x) (u32)(*(const u32 *)(x))
#define QWORD(x) (*(const u64 *)(x))
#endif /* ALIGNMENT_WORKAROUND || BIGENDIAN */
```

**Comment by bgoglin** [comment]
I pushed the fix so that I can release rc2 and get more testing. Hopefully I'll get clarification from DMTF one day. BE platforms are rare and SMBIOS requires root access anwway, hence very few users should be affected if the fix isn't correct. At least, regression tests should work on BE now.

**Comment by xiongzubiao** [comment]
Sorry for the late reply (due to holiday). To be honest I have no knowledge about the endianness, but your solution by following the dmidecode implementation looks perfectly reasonable to me. Thanks a lot for the fix!

**Comment by bgoglin** [comment]
DMTF confirmed that SMBIOS fields are little endian unless explicitly stated otherwise (and the network-order note is only about UUID, which DMTF confirms is messy). So type-17 fields are little endian. We're good.
