### ISSUE TITLE
2.10.0-rc1 fails to build on QEMU Linux userland emulation

### ISSUE THREAD

**Issue by sthibaul** [open-mpi/hwloc#638]
See https://buildd.debian.org/status/fetch.php?pkg=hwloc&arch=hppa&ver=2.10.0~rc1-2&stamp=1700747155&raw=0
 (the smbios patch is applied). It is not too concerning because hppa is not a debian release arch, but probably worth investigating.

-rc2 fails too: https://buildd.debian.org/status/fetch.php?pkg=hwloc&arch=hppa&ver=2.10.0~rc2-1&stamp=1700750376&raw=0

**Comment by bgoglin** [comment]
Not sure why this didn't break earlier.
qemu-hppa intercepts accesses to /proc/cpuinfo to return a HPPA-like CPU instead of the real x86 platform it runs on. test-hwloc-gather however seems to either fail to copy that custom file in the dump or to read it from the dump, since it gets the x86 cpuinfo instead.
I don't have all the infrastructure to reproduce and debug further, but we may just want to disable that test with HWLOC_TEST_GATHER_TOPOLOGY=0 in the environment since it is not clear it may actually be compatible with that qemu interception.

**Comment by sthibaul** [comment]
> it may actually be compatible with that qemu interception.

It would still be important to raise the issue to qemu, which is not supposed to leak the host processor details.

**Comment by sthibaul** [comment]
I managed to set up hppa multi-arch support on my machine and reproduced the problem, I'm dig a bit

**Comment by sthibaul** [comment]
https://gitlab.com/qemu-project/qemu/-/issues/2004

**Comment by sthibaul** [comment]
The interesting thing is that in a cross-build environment, the test actually erroneously passes :) Because the (non-cross) `cat` command gets the host content (as it should), and the (cross) `openat()` gets the host content (while it shouldn't) :)

**Comment by sthibaul** [comment]
Ok, fixed with https://salsa.debian.org/debian/hwloc/-/commit/dfe9659132fbcac1df7ae2dd08c15e39f2ddeb00

**Comment by bgoglin** [comment]
Whaout thanks :)
