### ISSUE TITLE
Count memory tiers with command line tool

### ISSUE THREAD

**Issue by antoine-morvan** [open-mpi/hwloc#661]
Hello, 

I was playing with the recent introduction of memory tiers. I am still looking for the command that would give me the number of memory tiers available on the machine. Does any of the command line tool provide such feature ?

My current workaround is to count with something like this : 
```sh
TIERCOUNT=$(lstopo -v | grep -i tier | rev | cut -d' ' -f1 | sort -u | wc -l) # or some awk / perl / etc.
[ $TIERCOUNT == 0 ] && TIERCOUNT=1 # since memory tiers are only shown when there are more than 1
```

Best.

**Comment by bgoglin** [comment]
Hello. There's currently no way, mostly because there's no API to query tiers (and there likely won't be before 3.0). 
Given that Tiers are currently an object info attribute only, we could have another global attribute with that number. In 2.x in would be machine object info, retrievable from the command-line with:
```
$ hwloc-info root | sed -n -e 's/ info MemoryTiersNr = //p'
```
In 3.0 it would be a topology info:
```
$ hwloc-info --topology -v | sed -n -e 's/info MemoryTiersNr = //p'
```
I can easily add this for 2.11.

**Comment by bgoglin** [comment]
I think I'll add an option to get a single attribute to hwloc-info and make it work with that syntax for both 2.x and 3.0. Something like:
```
$ hwloc-info --attr "info MemoryTiersNr" topology
```

**Comment by antoine-morvan** [comment]
To be honnest, I initially  looked for a syntax like `hwloc-calc --number-of tier machine:0`  :)

**Comment by bgoglin** [comment]
That would require much more since we'd need to emulate a fake "tier" object to count them, hwloc-calc doesn't know how to do that at all. And it would be quite annoying to implement for anything but machine:0.

**Comment by bgoglin** [comment]
I am posting 2.11rc1 right now with these changes.
