### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [open-mpi/hwloc#670]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7199362572#L7222 with Java 17

Also tried Java 11 and Java 8 but didn't help

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/0e8a9e805751f89847b33875362c78d1e80f3103

**Comment by bgoglin** [comment]
Hello. It's my first time hwloc build fails since it was added to fdroid, hence I am not sure if there are some obvious candidates to look at. Does this usually mean that I need to upgrade my gradle version? (4.10.1) I didn't change anything in the android build stuff recently. Did anything change on the fdroid side? The java version?

**Comment by bgoglin** [comment]
Ok so you upgraded your java from 11 to 17, that was my question. My build machine has no issue with both java 11 and 17, but I only using gradlew bundleRelease for google play store there, I'll run some real fdroid tests.

**Comment by bgoglin** [comment]
My old build machine didn't have any problem with fdroid or google play builds but it was too old to upgrade, so I deployed a new VM with a recent android studio etc. Now both fdroid and google play now fail with:
```
> Failed to notify project evaluation listener.
   > Could not initialize class com.sun.xml.bind.v2.runtime.reflect.opt.Injector
```
This is on Java 21. Java 17 fails with a different error. Tried with a recent gradle instead of our old 4.10, no luck.

It's not related to the new hwloc 2.11 release, the previous release fails the same (there's no Android related change in this release anyway). Something changed in the Android build stuff but I have no idea how to debug this further are java errors are useless as usual.

**Comment by linsui** [comment]
You also need to update AGP.

**Comment by bgoglin** [comment]
> You also need to update AGP.

Is this something to change inside my project/build or inside the Android Studio install? Android Studio is 2024.1.

**Comment by linsui** [comment]
It's https://github.com/open-mpi/hwloc/blob/master/contrib/android/AndroidApp/build.gradle#L10. When you update gradle, you also need to update this.

**Comment by bgoglin** [comment]
Thanks @linsui I managed to get things to work with gradle 8.8 and APG 8.5 (and after fixing some random stuff in the code). One hopefully-last thing to understand: Do you have any recommendation about the ndk version to use? my fdroid yaml currently says r20 but Android Studio seems to rather use 26.1. I don't know if upgrading this is recommended too.

**Comment by linsui** [comment]
Any ndk versions work for us. :)

**Comment by bgoglin** [comment]
> Any ndk versions work for us. :)

So do you even specify any in the yaml? Right now I have r20, but Android Studio actually installs in Android/Sdk/ndk/20.0.5594570 and I have to create a symlink "r20" for fdroid build to find. If I just remove "ndk: r20" from the yaml, it builds fine (and I don't even know if it used r20 or r26)

**Comment by licaon-kter** [comment]
Do you even used the NDK?

**Comment by linsui** [comment]
It works, thanks!

**Comment by bgoglin** [comment]
Oh you fixed the metadata upstream already, great!
Thanks to both of you for the help.
