### ISSUE TITLE
get_last_memory_location()

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#97]
```
hwloc_get_last_memory_location(hwloc_topology_t topology, const void *addr, size_t len, hwloc_nodeset_t nodeset)
```

And maybe another one with a PID (which would retrieve the entire address space location?).

This would set a bit in nodeset if a page in the range is allocated on the corresponding node.

The drawback is that this doesn't tell us if the pages are 50% across two nodes, or 99%-1%, or 1% on one 1% on the other and 98% not physically allocated. Maybe have a way to return an array on node* corresponding to each page (NULL if not allocated) like Linux move_pages syscall does.

To avoid the drawback, we could remove the "length" attribute and just give the location of a single address (got another user request for this one):
```
hwloc_get_last_memory_location(hwloc_topology_t topology, const void *addr, hwloc_nodeset_t nodeset)```

**Comment by bgoglin** [comment]
Somehow requested in http://www.open-mpi.org/community/lists/hwloc-users/2015/12/1225.php

**Comment by bdboyraju** [comment]
Hi I was interested to know the status of implementation as stated previously, 
hwloc_get_last_memory_location(hwloc_topology_t topology, const void *addr, hwloc_nodeset_t nodeset)

and is any insight about the issue talks here: http://www.open-mpi.org/community/lists/hwloc-users/2015/12/1225.php

Thanks.! 
- Raju

**Comment by bgoglin** [comment]
Not implemented yet since I don't know which prototype is more useful among the ones proposed above.
Once implemented, the related commits will automatically be referenced here, and the issue will get closed automatically as well.

**Comment by bgoglin** [comment]
I pushed a proposal to the getmemlocation branch. The API is https://github.com/open-mpi/hwloc/blob/getmemlocation/include/hwloc.h#L1636

The name should have been hwloc_get_area_last_memory_location() but I found it too long.

It returns a bitmask describing the nodes that contain some memory of the given address range inside the current process. It won't tell you whether each node has 1% or 50% of these pages. But that's likely enough for most uses (people want this feature to that check memory allocations went to the right node).

It only works for the current process because querying a specific memory range in another process didn't seem very useful.

Querying the entire memory space of another process could be useful but it would be very expensive on Linux (need to query every page in the address space), and shared libraries could be allocated anywhere anyway.
